### PR TITLE
Quality of Life Improvement: Updated sca.py menu

### PR DESCRIPTION
**Pull request by bdorney**
## Description

I had structured the `ArgumentParser` in a manner that required the user to supply the `cardName` and `ohMask` to get the help menu for a subcommand.

This is obviously not ideal.  I've resolved this issue. 

Supersedes #45, this PR addresses issues #43 and #44.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

Fixing bad design.

## How Has This Been Tested?

Change was trivial.

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by mexanick — DISMISSED** [review]

**Review by jsturdy — CHANGES_REQUESTED** [review]
The duplication of the arguments gives me great pause.
Can something like [this](https://stackoverflow.com/questions/33645859/how-to-add-common-arguments-to-argparse-subcommands) work in this case?

(I checked and it does seem to work as desired)
```bash
./argtester.py card 123 h -h
usage: argtester.py [-h] {compare-mcs-bit,h,hh} ...
argtester.py: error: invalid choice: 'card' (choose from 'compare-mcs-bit', 'h', 'hh')

./argtester.py h -h         
usage: argtester.py h [-h] cardName ohMask

positional arguments:
  cardName    hostname of the AMC you are connecting too, e.g. 'eagle64'; if
              running on an AMC use 'local' instead
  ohMask      ohMask to apply, a 1 in the n^th bit indicates the n^th OH
              should be considered

optional arguments:
  -h, --help  show this help message and exit
```

**Update**: this *does* change slightly the usage, as the command comes before **any** arguments...

**Comment by jsturdy** [comment]
bump @bdorney

**Comment by bdorney** [comment]
Thanks for reminder.  Busy with connectivity testing routine and training QC8'ers.  WIP still.

**Comment by bdorney** [comment]
@jsturdy @mexanick added a parent parser to reduce option duplication.

**Review by mexanick — APPROVED** [review]

**Comment by bdorney** [comment]
@jsturdy parent parser was implemented.

**Review by jsturdy — APPROVED** [review]
> **Update**: this _does_ change slightly the usage, as the command comes before **any** arguments...

Has the slight required usage change been documented/announced to users (sure, it's available in the `help` but ...)

**Comment by bdorney** [comment]
~~Short answer “no.”~~

~~I could make a pinned post in Mattermost referencing a new usage example and an email to the online SW egroup. Would this be suitable?~~

**Comment by bdorney** [comment]
@jsturdy I've notified the users; could you point me to the GEMDOC twiki page so I can also update the usage example there?  I don't have my bookmarks...

**Pull request merged**
